-- মানবকল্যাণ যুব সংঘ — Public finance database
create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('income','expense')),
  amount numeric(12,2) not null check (amount > 0),
  title text not null,
  donor_name text,
  note text,
  transaction_date date not null default current_date,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid()
);

alter table public.transactions enable row level security;

drop policy if exists "Public can read transactions" on public.transactions;
create policy "Public can read transactions" on public.transactions
for select using (true);

drop policy if exists "Authenticated admins can insert" on public.transactions;
create policy "Authenticated admins can insert" on public.transactions
for insert to authenticated with check (auth.uid() is not null);

drop policy if exists "Authenticated admins can update" on public.transactions;
create policy "Authenticated admins can update" on public.transactions
for update to authenticated using (auth.uid() is not null) with check (auth.uid() is not null);

drop policy if exists "Authenticated admins can delete" on public.transactions;
create policy "Authenticated admins can delete" on public.transactions
for delete to authenticated using (auth.uid() is not null);

insert into public.transactions (type, amount, title, donor_name, note, transaction_date)
select 'income', 1000, 'প্রাথমিক অনুদান', 'ডেমো', 'ডেমো রেকর্ড—চাইলে মুছে দিন', current_date
where not exists (select 1 from public.transactions);
